export const data = [
  {
    id: 1,
    cost: 9490,
    x: -30,
    y: -66,
    name: '고향만두_1650G',
    manu: '해태',
    viewcost: '9490원',
    imgSrc: require('./imgs/1.jpg'),
  },
  {
      id: 2,
      cost: 11900,
      x: 108,
      y: -132,
      name: '다우니퍼퓸볼륨_2L',
      manu: 'P&G',
      viewcost: '11900원',
      imgSrc: require('./imgs/2.jpg'),
    },
  {
      id: 3,
      cost: 5490,
      x: -21,
      y: -230,
      name: '당근_500G봉',
      manu: '친환경',
      viewcost: '5490원',
      imgSrc: require('./imgs/3.jpg'),
    },
  {
      id: 4,
      cost: 3290,
      x: 94,
      y: -231,
      name: '돼지삼겹살_100G',
      manu: '백두한돈',
      viewcost: '3290원',
      imgSrc: require('./imgs/4.jpg'),
    },
  {
      id: 5,
      cost: 4750,
      x: -61,
      y: -66,
      name: '맛있는우유GT_900ML*2',
      manu: '남양',
      viewcost: '4750원',
      imgSrc: require('./imgs/5.jpg'),
    },
  {
      id: 6,
      cost: 4680,
      x: 18,
      y: -67,
      name: '백산수_2L(6입)',
      manu: '농심',
      viewcost: '4680원',
      imgSrc: require('./imgs/6.jpg'),
    },
  {
      id: 7,
      cost: 3980,
      x: -1,
      y: -177,
      name: '불닭볶음면_140G*5입',
      manu: '삼양',
      viewcost: '3980원',
      imgSrc: require('./imgs/7.jpg'),
    },
  {
        id: 8,
        cost: 14900,
        x: 91,
        y: -67,
        name: '비비고총각김치_1.5KG',
        manu: 'CJ',
        viewcost: '14900원',
        imgSrc: require('./imgs/8.jpg'),
      },
  {
        id: 9,
        cost: 7900,
        x: 82,
        y: -131,
        name: '살코기참치_150G*3',
        manu: '동원',
        viewcost: '7900원',
        imgSrc: require('./imgs/9.jpg'),
      },
  {
        id: 10,
        cost: 5650,
        x: -58,
        y: -65,
        name: '생크림_500ML',
        manu: '서울',
        viewcost: '5650원',
        imgSrc: require('./imgs/10.jpg'),
      },
  {
        id: 11,
        cost: 9900,
        x: -95,
        y: -66,
        name: '스트링치즈_180G',
        manu: '매일',
        viewcost: '9900원',
        imgSrc: require('./imgs/11.jpg'),
      },
  {
        id: 12,
        cost: 2490,
        x: 40,
        y: -66,
        name: '스프라이트_1.5L',
        manu: '코카콜라',
        viewcost: '2490원',
        imgSrc: require('./imgs/12.jpg'),
      },
  {
        id: 13,
        cost: 3380,
        x: -5,
        y: -111,
        name: '신라면_120G*5입',
        manu: '농심',
        viewcost: '3380원',
        imgSrc: require('./imgs/13.jpg'),
   },
  {
        id: 14,
        cost: 7990,
        x: -17,
        y: -66,
        name: '안심치킨 너겟_540G',
        manu: '대림',
        viewcost: '7990원',
        imgSrc: require('./imgs/14.jpg'),
   },
  {
        id: 15,
        cost: 1290,
        x: 25,
        y: -111,
        name: '양조식초_1.5L',
        manu: '오뚜기',
        viewcost: '1290원',
        imgSrc: require('./imgs/15.jpg'),
   },
   {
        id: 16,
        cost: 7900,
        x: 106,
        y: -167,
        name: '엘라스틴퍼퓸러브미샴푸_600ML',
        manu: 'LG',
        viewcost: '7900원',
        imgSrc: require('./imgs/16.jpg'),
      },
   {
           id: 17,
           cost: 3990,
           x: 82,
           y: -175,
           name: '옛날자른미역_50G(봉)',
           manu: '오뚜기',
           viewcost: '3990원',
           imgSrc: require('./imgs/17.jpg'),
      },
   {
           id: 18,
           cost: 1000,
           x: -54,
           y: -160,
           name: '왕고래밥볶음양념_56G',
           manu: '오리온',
           viewcost: '1000원',
           imgSrc: require('./imgs/18.jpg'),
      },
  {
          id: 19,
          cost: 3990,
          x: -51,
          y: -230,
          name: '조각양배추',
          manu: '친환경',
          viewcost: '3990원',
          imgSrc: require('./imgs/19.jpg'),
     },
   {
         id: 20,
         cost: 1280,
         x: 50,
         y: -67,
         name: '참이슬_360ML',
         manu: '하이트진로',
         viewcost: '1280원',
         imgSrc: require('./imgs/20.jpg'),
    },
   {
           id: 21,
           cost: 9990,
           x: -82,
           y: -229,
           name: '청송사과_4-6입(봉)',
           manu: '유명산지',
           viewcost: '9990원',
           imgSrc: require('./imgs/21.jpg'),
      },

  {
          id: 22,
          cost: 3390,
          x: 24,
          y: -132,
          name: '청정원구운소금_500G',
          manu: '대상',
          viewcost: '3390원',
          imgSrc: require('./imgs/22.jpg'),
     },

  {
          id: 23,
          cost: 8990,
          x: 23,
          y: -155,
          name: '청정원순창찰고추장_1KG',
          manu: '대상',
          viewcost: '8990원',
          imgSrc: require('./imgs/23.jpg'),
     },
  {
          id: 24,
          cost: 3380,
          x: -53,
          y: -131,
          name: '초코하임_284G',
          manu: '크라운',
          viewcost: '3380원',
          imgSrc: require('./imgs/24.jpg'),
     },
  {
          id: 25,
          cost: 5490,
          x: 26,
          y: -66,
          name: '코카콜라_1.8L*2',
          manu: '코카콜라',
          viewcost: '5490원',
          imgSrc: require('./imgs/25.jpg'),
     },
  {
          id: 26,
          cost: 1990,
          x: 25,
          y: -186,
          name: '큐원갈색설탕_1KG',
          manu: '삼양사',
          viewcost: '1990원',
          imgSrc: require('./imgs/26.jpg'),
     },
  {
          id: 27,
          cost: 8220,
          x: 41,
          y: -67,
          name: '테라_355ML*6',
          manu: '하이트진로',
          viewcost: '8200원',
          imgSrc: require('./imgs/27.jpg'),
     },
  {
          id: 28,
          cost: 2990,
          x: 25,
          y: -66,
          name: '파워에이드마운틴_1.5L',
          manu: '코카콜라',
          viewcost: '2990원',
          imgSrc: require('./imgs/28.jpg'),
     },
  {
          id: 29,
          cost: 1000,
          x: -52,
          y: -143,
          name: '포카칩오리지날_66G',
          manu: '오리온',
          viewcost: '1000원',
          imgSrc: require('./imgs/29.jpg'),
     },
  {
          id: 30,
          cost: 9900,
          x: 92,
          y: -229,
          name: '훈제오리슬라이스_600G(팩)',
          manu: '산야초',
          viewcost: '9900원',
          imgSrc: require('./imgs/30.jpg'),
     },
]